In [8]:
from IPython.core.display import SVG


# Regression Loss Functions

scoring function: $|\textbf{W}.\textbf{X}_i+b|$

### 1) Mean Absolute Error Loss
Treats outlier like anyother point so it won't go out of its way for outliers which might lead to poor prediction from time to time. Also it is not optimized for gradient descent (due to incontinuty on zero)Support vector regression use this.

### 2) Mean Squared Error Loss
The adventage is we can easily compute gradient for ML. Good for regression but outlier will make it a poor model

### 3) Pseudo-Huber Loss
Mean Absolute Error doenst comply with outlier and Mean Squared Error freaks out with outlier. If your data is 70% on one side and 30% on the other side, both will reult in a poor model.

### 4) Welsch (Leclerc)


### 5) Geman McClure


### 6) Causchy


# Classification Loss Functions


### 1) Cross-Entropy Loss
When we use <b>sigmoid</b> as activation function and <b>Mean Squared Error Loss</b>, if our neuron output is very wrong ,since $\sigma(z)$ s saturated and it is almost a flat line ($z \to \infty$, $\sigma(z) \to 1$ and $z \to -\infty$, $\sigma(z) \to 0$) , $\sigma'(z)$ gives us a small value so learning will be very slow. 
<b>Cross-Entropy Loss</b> designed for binary classifiers. In a binary classifier,  $y \in \{0,1\}$ is the class lable and $a$ is the output of the activation function (could be any number).


$\begin{eqnarray}\frac{\partial C}{\partial w} & = & (a-y)\sigma'(z) x = a \sigma'(z)\end{eqnarray}$
  
$\begin{eqnarray}\frac{\partial C}{\partial b} & = & (a-y)\sigma'(z) = a \sigma'(z),\end{eqnarray}$

Let say we have binary classifier, so we have 1 output node and the class labeles are either 1 or 0, 
$C=-\frac{1}{n} \sum_{x} y\ln(a)+ (1-y)\ln(1-a)$


### 2) Multi-Class Cross-Entropy Loss
If we have $j$ output in the last layer $L$, the total cost for all inputs is:

$\begin{eqnarray}  C = -\frac{1}{n} \sum_x
  \sum_j \left[y_j \ln a^L_j + (1-y_j) \ln (1-a^L_j) \right].
\end{eqnarray} $

One way to remmeber that the order is  $ y_j \ln a^L_j$ and not other way around is to remmeber that $y_j$ could be 
absoulute zero so it can't be the parameter for logarithm function, but $a^L_j$ can $\lim a^L_j \to 0 $, so it is the parameter of $\ln$

Now lets compute the the $\delta$ when the loss function is **Multi-Class Cross-Entropy Loss** and activation function is **sigmoid**:


$\delta_j=\begin{eqnarray}
  \frac{\partial C}{\partial z_j} &=\frac{\partial C}{\partial a_j}\frac{\partial a_j}{\partial z_j}   = & -\frac{1}{n} \sum_x \left(
    \frac{y }{\sigma(z_j)} -\frac{(1-y)}{1-\sigma(z_j)} \right)\sigma'(z_j) 
& = & -\frac{1}{n} \sum_x \left( 
    \frac{y -\sigma(z_j)}{\sigma(z_j)(1-\sigma(z_j))}
    \right).\sigma(z_j)(1-\sigma(z_j))
\end{eqnarray}$

Reminder: for sigmoid activation function:

$\sigma'(z_j)=\sigma(z_j)(1-\sigma(z_j))$


So we would have:


$\begin{eqnarray} 
    \delta^L = a^L-y.\tag 1
\end{eqnarray}$

Reminder: in quadratic loss function, $\delta$ was:

$\delta^L= 2(\textbf{a}^{(L)}-\textbf{y}) \odot   \sigma^{\prime}(\textbf{z}^{(L)})$

For previous layer $L-1, L-2,...$, the $\delta^{(L-1)}$ is same as wath we computed before in network with quadratic loss function

$\begin{eqnarray} 
      \frac{\partial C}{\partial w^L_{jk}} & = & \frac{1}{n} \sum_x 
      a^{L-1}_k  (a^L_j-y_j) \tag 2
\end{eqnarray}$

This tells us that the rate at which the weight learns is controlled by $\sigma(z)-y$ (by the error in the output). The larger the error, the faster the neuron will learn. This avoids the learning slowdown caused by the $\sigma '(z)$ term in the analogous equation for the quadratic cost,

$\begin{eqnarray}
      \frac{\partial C}{\partial b^L_{j}} & = & \frac{1}{n} \sum_x 
      (a^L_j-y_j).
  \tag{3}\end{eqnarray}$


### 3) Negative log likelihood

The <b>Negative Log-Likelihood Loss function (NLL)</b> is applied only on models with the softmax function as an output activation layer. We can think a softmax output layer with log-likelihood cost as being quite similar to a sigmoid output layer with cross-entropy cost.

The Softmax function is :




${\displaystyle \sigma (\mathbf {z} )_{i}={\frac {e^{z_{i}}}{\sum _{j=1}^{K}e^{z_{j}}}}}$


The softmax function takes an input vector of size $N$, and then modifies the values such that every one of them falls between 0 and 1.


$NLL$ uses a negative connotation since the probabilities (or likelihoods) vary between zero and one, and the logarithms of values in this range are negative. In the end, the loss value becomes positive. The negative log likelihood is retrieved from approximating the maximum likelihood estimation $MLE$. This means that we try to maximize the model’s log likelihood, and as a result, minimize the $NLL$.  

Neural network estimate: 
$f(X)_c=p(y=c|X)$

Which means NN estimate the probability that the output of network, $y$ for the given vector $X$ is the correct class $c$.
For instance we have 3 classes, which means 3 nodes at the output layer, and for a given input we get:
$(0.1,0.85,0.05 )$, which means which means our network belives with the probability of $0.85$ this input belong to the second class. Since the inputs are independent of each other the joint probability of them would be teh multipication of them just like $MLE$. Since output probabilities are betwen zero and one the $ln$ of them would be a negative value, so we turn them into positive number by multiplying tem by a negative number and we turn maximisation problem into minimization.

$l(\textbf{f}(X),y)=-ln f(X)_c=-\Sigma_c 1_{y=c}ln(f(X)_c)$


Refs:

[1](https://www.youtube.com/watch?v=PpFTODTztsU), [2](https://neptune.ai/blog/pytorch-loss-functions),
[3](https://ljvmiranda921.github.io/notebook/2017/08/13/softmax-and-the-negative-log-likelihood/)

In [4]:
import torch
import torch.nn as nn
# size of input (N x C) is = 3 x 5
#N
number_of_item_in_training_set=3

#C
number_of_neuron_in_output_layer=5

input = torch.randn(number_of_item_in_training_set, number_of_neuron_in_output_layer, requires_grad=True)

# target should have only 3 elements (N=3) and every element in target should have 0 <= value < C=5
# because these are target lables. Target: (N)
target = torch.tensor([4, 3, 2])

m = torch.nn.LogSoftmax(dim=1)

# NLLLoss expects the inputs to be log probabilities
nll_loss = torch.nn.NLLLoss()
output = nll_loss(m(input), target)
output.backward()

print('input: \n', input)
print('target: \n', target)
print('output: \n', output)
print('m(input).exp()\n',m(input).exp())

input: 
 tensor([[-1.3344,  1.1074,  1.4426,  2.6769,  0.0471],
        [ 0.4339,  0.8847, -1.0222, -2.1679,  0.1310],
        [ 2.1894, -0.8627,  0.2758,  0.7876,  0.6859]], requires_grad=True)
target: 
 tensor([4, 3, 2])
output: 
 tensor(3.1342, grad_fn=<NllLossBackward>)
m(input).exp()
 tensor([[0.0114, 0.1310, 0.1831, 0.6292, 0.0454],
        [0.2766, 0.4341, 0.0645, 0.0205, 0.2043],
        [0.6012, 0.0284, 0.0887, 0.1480, 0.1337]], grad_fn=<ExpBackward>)


In [5]:
loss = nn.NLLLoss()
a = torch.tensor(([0.88, 0.12], [0.51, 0.49]), dtype = torch.float)
target = torch.tensor([1, 0])
output = loss(torch.log(a), target)
print(output)

print((-torch.log(a[0, 1]) - torch.log(a[1, 0])) / 2)


tensor(1.3968)
tensor(1.3968)


### 4) Hinge Loss
Let's say we have binary classifier with two labels, $-1,+1$ to measure the misclassification error:

$\frac{1}{n}\sum_{i=1}^{n}[y_i\neq  sign(f(x_i))] = \frac{1}{n}\sum_{i=1}^{n}[y_i f(x_i)] \leq \frac{1}{n}\sum_{i=1}^{n}L(y_i f(x_i)) $

minimizing this error function is computationaly complicated so 

Mainly used in SVMm which set a boundry as far as possible between all data points (maximizes the minimum margin).
It will penalized the points even they are in the margin.


scoring function: $|\textbf{W}.\textbf{X}_i+b|$

Training test label, $y_i = ±1$

$L_i=max(0,1-y_i|\textbf{W}.\textbf{X}_i+b|)$


Refs: [1](https://www.youtube.com/watch?v=r-vYJqcFxBI)

<img src='images/hinge.svg' />

## Adaptive Loss Functions
All the abve loss functions can be generalized by:

$p(x,\alpha)=\frac{|2- \alpha|}{\alpha} \left (   \left ( \frac{x^2}{|2-\alpha|}+1  \right )^{\alpha/2}  -1 \right )  $


$NLL(\theta,\alpha)=min \rho_{\theta,\alpha} (x,\alpha )+logZ(\alpha) $



Refs: [1](https://arxiv.org/abs/1701.03077), [2](https://www.youtube.com/watch?v=QBbC3Cjsnjg), [3](https://medium.com/udacity-pytorch-challengers/a-brief-overview-of-loss-functions-in-pytorch-c0ddb78068f7), [4](https://rohanvarma.me/Loss-Functions/), [5](https://towardsdatascience.com/common-loss-functions-in-machine-learning-46af0ffc4d23), [6](https://neptune.ai/blog/pytorch-loss-functions), [7](https://www.youtube.com/watch?v=ErfnhcEV1O8)