# PyTorch Coding Conventions
`PEP 8` style mostly applies to pytorch, so the followings are the conventions and guidelines.
## Importing modules
**Correct**

In [ ]:
import os
import sys

**Wrong**

In [ ]:
import sys, os

## Classes
should normally use the CapWords convention., However, it still seems that builtin or extension types written
in C are more likely to have lowercase names (e.g., numpy.array, not numpy.Array).

## Package and Module Names
Modules should have short, all-lowercase names.

## Type Variable Names
Names of type variables introduced use CapWords

## Function and Variable Names
Function names should be lowercase, with words separated by underscores as necessary to improve readability.

## Constants
Constants are usually defined on a module level and written in all capital letters with underscores
separating words. Examples include MAX_OVERFLOW and TOTAL.

Refs [1](https://www.python.org/dev/peps/pep-0008/)


# Pytorch Modules (torch.nn) vs Functions  (torch.nn.functional)

The modules in `torch.nn` can be added or connected to other layers or network models.

The `torch.nn.Functional` contains some useful functions like some arithmetical operations, activation functions, convolution operations, etc. However, these are not full layers so if you want to specify a layer of any kind you should use `torch.nn.Module.` The functions in `torch.nn.functional` are not the layers which have trainable parameters such as weights and bias terms.




# Modules (torch.nn.Module)
List of modules:

- torch.Tensor()
- torch.nn.Conv2d()
- torch.nn.ReLU()
- torch.nn.Softmax()
- torch.nn.Dropout()
- torch.nn.Linear()

# Functions (torch.nn.Functional)
List of functions:

- torch.tensor(data=[2,3], dtype=torch.float32, device=device , requires_grad=False)
- torch.nn.functional.conv2d()
- torch.nn.functional.relu()
- torch.nn.functional.softmax()
- torch.nn.functional.dropout()
- torch.nn.functional.linear()


# Tensors
A `torch.Tensor` is a multi-dimensional matrix containing elements of a single data type. `torch.Tensor` is an alias for the default tensor type (`torch.FloatTensor`).

## Pytorch Data types and Tensor types
Listf of most important data types:

   

Data type            |dtype =torch.dtype            | CPU tensor=torch.tensortype | GPU tensor=torch.tensortype
---                  |-----                         |-----                        |-----  
32-bit floating point|torch.float32 or torch.float  |torch.FloatTensor            |torch.cuda.FloatTensor
64-bit floating point|torch.float64 or torch.double |torch.DoubleTensor           |torch.cuda.DoubleTensor





In [7]:
import torch
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')

a=torch.tensor(data=[2.0,3.0])
print("Data type (torch.tensortype): ",a.type())
print("dtype (torch.dtype):", a.dtype)


Data type (torch.tensortype):  torch.cuda.FloatTensor
dtype (torch.dtype): torch.float32


### Moving tensor to device

In [8]:
a=a.to(device)
print("Data type (torch.tensortype): ",a.type())
print("dtype (torch.dtype):", a.dtype)

Data type:  torch.cuda.FloatTensor
dtype torch.float32


### Creating tensor on GPU

In [9]:
a=torch.tensor(data=[2.0,3.0], dtype=torch.float32, device=device)
print("Data type (torch.tensortype): ",a.type())
print("dtype (torch.dtype):", a.dtype)

Data type:  torch.cuda.FloatTensor
dtype torch.float32


### Creating tensor on CPU

In [12]:
a=torch.tensor(data=[2.0,3.0], dtype=torch.float32, device=torch.device('cpu'))
print("Data type (torch.tensortype): ",a.type())
print("dtype (torch.dtype):", a.dtype)


Data type (torch.tensortype):  torch.FloatTensor
dtype (torch.dtype): torch.float32


### Tesnor vs tensor

In [14]:
# torch.Tensor is an alias for the default tensor type (torch.FloatTensor).
a=torch.Tensor(data=[2.0,3.0])
print("Data type: ",a.type())
print("dtype", a.dtype)

Data type:  torch.cuda.FloatTensor
dtype torch.float32


### Settings default tensor type

In [13]:
torch.set_default_tensor_type('torch.cuda.FloatTensor')
a=torch.tensor(data=[2.0,3.0] )
print("Data type (torch.tensortype): ",a.type())
print("dtype (torch.dtype):", a.dtype)

Data type (torch.tensortype):  torch.cuda.FloatTensor
dtype (torch.dtype): torch.float32


[List of data types](https://pytorch.org/docs/master/tensors.html)

## Named Tensor

In [17]:
imgs = torch.randn(1, 2, 2, 3 , names=('N', 'C', 'H', 'W'))
print(imgs.names)

renamed_imgs = imgs.rename(H='height', W='width')
print(renamed_imgs.names)

imgs = torch.randn(1, 2, 2, 3 , names=(None, 'C', 'H', 'W'))

# Two names match if they are equal (string equality) or if at least one is None

x = torch.randn(3, names=('X',))
y = torch.randn(3)
z = torch.randn(3, names=('Z',))

x + y
# error
#x + z
x + x

('N', 'C', 'H', 'W')
('N', 'C', 'height', 'width')


<ipython-input-17-f372d359699e>:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /opt/conda/conda-bld/pytorch_1616554788289/work/c10/core/TensorImpl.h:934.)
  imgs = torch.randn(1, 2, 2, 3 , names=('N', 'C', 'H', 'W'))


tensor([-0.6034, -5.5537,  0.0113], names=('X',))

Refs [1](https://pytorch.org/docs/stable/named_tensor.html)

# CUDA/ GPU infomation

In [16]:
# Make Sure That Pytorch Using GPU To Compute
import torch
import os


if(torch.cuda.is_available()):
    print('cuda is available')
    print('cuda device count',torch.cuda.device_count())
    print('current device is:',torch.cuda.current_device())
    print('device name',torch.cuda.get_device_name(0))
    print('nvcc version: ')
    os.system('nvcc --version')
    print('nvidia-smi:')
    os.system('nvidia-smi')


cuda is available
cuda device count 1
current device is: 0
device name GeForce MX150
nvcc version: 
nvidia-smi:


## Operation on Tensor
### view()
PyTorch allows a tensor to be a View of an existing tensor (sharing the same underlying data with its base tensor, avoids explicit data copy) 

In [18]:
x=torch.rand(2,6)
print(x[0][0])
y=x.view(4,3)
y[0][0]=1.0
print(x[0][0])

tensor(0.7549)
tensor(1.)


### transpose()

In [21]:
x = torch.randn(2, 3)
print(x) 

print(torch.t(x)) 

print(torch.transpose(x, 0, 1))

tensor([[-1.2405, -0.7458,  0.4639],
        [-1.7821,  2.1286, -2.7806]])
tensor([[-1.2405, -1.7821],
        [-0.7458,  2.1286],
        [ 0.4639, -2.7806]])
tensor([[-1.2405, -1.7821],
        [-0.7458,  2.1286],
        [ 0.4639, -2.7806]])


### contiguous()
### is_contiguous()
### expand()
### narrow()
### squeeze()
### values() 
### detach()
### is_pinned()
### is_shared()


### item()
Use t`orch.Tensor.item()` to get a Python number from a tensor containing a single value

Refs: [1](https://pytorch.org/docs/master/tensor_view.html)